spring:
    datasource:
        url: jdbc:mariadb://localhost:3307/LibraryManager
        username: root
        password: black
        driver-class-name: org.mariadb.jdbc.Driver
    jpa:
        show-sql: true
        properties:
            hibernate.format_sql: true               
            database: mariadb
            hibernate.hbm2ddl.auto: update
            database-platform: org.hibernate.dialect.MariaDBDialect
    application:
        name: Library-Manager 
server:
    servlet:
        context-path: /api